### ISSUE TITLE
Move the DB code into a separate DB folder

### ISSUE THREAD

**Issue by paloobi** [dyazdani/costume-shop-db#24]

**Comment by paloobi** [comment]
@dyazdani this is a good way to ask questions on a GitHub project. This is great because now this conversation is documented so you can remember what you talked about later

**Comment by dyazdani** [comment]
Decided not to make a PR for this since it was just a simple moving of files.

**Comment by paloobi** [comment]
> Decided not to make a PR for this since it was just a simple moving of files.

The problem there is that it looks like it broke some tests. PR review might have caught that ;)

To be honest, moving files around is one of the most common ways of breaking things.

**Comment by paloobi** [comment]
btw remember to close issues once they are completed (if they are linked to a PR they will automatically be closed)

**Comment by dyazdani** [comment]
Yes! Thank you for reminding me about that.
