### ISSUE TITLE
Add API Router

### ISSUE THREAD

**Issue by paloobi** [dyazdani/costume-shop-db#37]
- [x] Create an `api` directory
- [x] Add an `index.ts` file to the directory
- [x] Create a router inside the api index
- [x] Add the router to your Express app middleware

**Comment by dyazdani** [comment]
@paloobi @AnthonyPinto Do you want us to add tests on this branch to test the api router? Or is that just for the GET, POTS, etc. adapaters?

**Comment by paloobi** [comment]
@dyazdani If you have a default route for just GET /api, you can write a test for it but I would leave the decision to you. It's not as important as testing the endpoints you plan to setup
